config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboards/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :companies do
    resources :comments, only: [:create, :destroy]
  end

  root 'companies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Compañias', companies_path %></li>
        <li><%= link_to 'Dashboard', dashboards_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in?  %>
              <strong>Bienvenido, </strong><%= current_user.name %>
            <% else %>
              <strong>Entrar</strong>
            <% end %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><a href="<%= edit_user_registration_path %>">Editar</a></li>
              <li class="divider"></li>
              <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Cerrar Sesión</a></li>
            <% else %>
              <li><a href="<%= new_user_session_path %>">Ingresar</a></li>
              <li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>