config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboards/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :companies do
    resources :comments, only: [:create, :destroy]
  end

  root 'companies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :comments

  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    @company = Company.new
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @comment = @company.comments.build
    @comments = @company.comments
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.js
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.js
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.js
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<tr id='<%= company.id %>'>
  <td><%= company.name %></td>
  <td><%= link_to 'Show', company, class: 'btn btn-info btn-sm' %>
  <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-warning btn-sm', remote: true %>
  <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'btn btn-danger btn-sm' %></td>
</tr>

app/views/companies/_form.html.erb
<%= form_for(company, remote: true) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Agregar Compañia', class: 'btn btn-success btn-sm' %>
  </div>

<% end %>

app/views/companies/_new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/create.js.erb
$("tbody").append("<%= j render @company %>");

app/views/companies/destroy.js.erb
$("#<%= @company.id %>").toggle(500);

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/edit.js.erb
$("#myModal").html("<%= j render "new"%>");
$('#myModal').modal('show');

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Companies</h1>
<div class="row">
  <div class="col-md-4">
    <%= render 'form', company: @company %>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <%= render company %>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12 text-center">
    <h3>Empresa: <strong><%= @company.name %></strong></h3>
      <hr>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <p>Total Reclamos: <%= @company.comments.count %></p>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-6">
    <%= form_for([@company, @comment], remote: true) do |f| %>

      <div class="form-group">
        <%= f.label :content, 'Ingresa un Comentario' %>
        <%= f.text_area :content, class: 'form-control' %>
        <br>
        <%= f.submit class: 'btn btn-success btn-sm' %>
      </div>

    <% end %>
    <br>
    <%= form_tag(company_path, method: :get) do %>
       <div class="input-group">
           <%= text_field_tag :search_comment, nil, placeholder: 'Ej: Reclamo de Carlos', class: "form-control" %>
           <span class="input-group-btn">
               <%= button_tag(type: "submit", class: "btn btn-success btn-md") do %>
                   <span class="glyphicon glyphicon-search"></span>
               <% end %>
           </span>
       </div>
       <% end %>
  </div>
  <div class="col-md-6">
    <p>Reclamos</p>
    <ul id="comments">
        <%= render @comments %>
    </ul>
  </div>
</div>
<br>
<%= link_to 'Back', companies_path %>

app/views/companies/update.js.erb
$("#myModal").html("<%= j render "new"%>");
$('#myModal').modal('show');